---
apiVersion: v1
kind: ConfigMap
metadata:
  name: radarr-4k-gatus-ep
  namespace: default
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: radarr-4k
        group: guarded
        url: 1.1.1.1
        interval: 1m
        dns:
          query-name: "radarr-4k.${SECRET_DOMAIN}"
          query-type: A
        conditions:
          - "len([BODY]) == 0"
        alerts:
          - type: pushover
