---
apiVersion: v1
kind: ConfigMap
metadata:
  name: qbittorrent-gatus-ep
  namespace: default
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: qbittorrent
        group: guarded
        url: 1.1.1.1
        interval: 1m
        dns:
          query-name: qb.brewcode.xyz
          query-type: A
        conditions:
          - "len([BODY]) == 0"
        alerts:
          - type: pushover
