---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd
  namespace: default
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-temp
  namespace: default
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
