---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app invidious-server
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"
    initContainers:
      01-init-db:
        image: ghcr.io/onedr0p/postgres-init:16.2
        imagePullPolicy: IfNotPresent
        envFrom: &envFrom
          - secretRef:
              name: &secret invidious-secret
    image:
      repository: quay.io/invidious/invidious
      tag: latest@sha256:afc535291949896b9014c418ffb70730fefd5bbf6697cf03ac8dbdbe99705632
    envFrom: *envFrom
    service:
      main:
        ports:
          http:
            port: 3000
    ingress:
      main:
        enabled: true
        ingressClassName: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.lumu.au
        hosts:
          - host: &host "invidious.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: false
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
