ansible_become_pass: ENC[AES256_GCM,data:N/IfLffLtquoqZ17,iv:/foKNnvhMWO2CZF/K+I9wRsdzs3yFCI+XtYQnqTlArE=,tag:EfHWhKOn2xZA8Jt4OGug6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zucujcrr89pecplrme76f4vxcc05lg3hm8849mmfggvcvcv4ppls7cquw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3SnRselBzNXdSRnRmYm1O
            R0JGTU1seU0xNG1NUGZrd1hyeWFOVkVMekVFCnZxOGJVcll5TWRNNCszZGJqY2o4
            b1NmUVhiQnR6RTZBUVdGK0lhdGZ3aVkKLS0tIEwwKzJlOExXVkF3ajlOZzMzTjcw
            TitweGtDS20vYWxtUUFJdDdIbGdDOVUK2UZtiIKBu0OSW9qYeGF/0K+MC/ARIUve
            6llAxmx8lqhNmYhRYaiOeRq22glVSEXtf+NRMElTJHz29NU/D3FkWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-23T04:35:10Z"
    mac: ENC[AES256_GCM,data:Sy8G0RAyQ5bHmNsu1Q8ijdvisj/b5F05K0uLf6y86tLrViGgK91ivO9nzcLAMZ0Kzhen0k3E97ueXIzTpa+fHakQRJHLic7kdHPeRKwMmCigygg3qJ1PR2uEmSd2mO9aHQnqjUAxU9rMDjb+fa3goVCJLkbtO9XN7UuGClq9YZ4=,iv:W0GxSQHAwyfwLZ399p9yMqvnxHkqyV7qIcITE4JpZWA=,tag:tvgKNDOMFhMAcPrUFcvZBg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
