ansible_become_pass: ENC[AES256_GCM,data:VgVPD7P17kieAtMD,iv:Iw84TkEPqlBqTRZ1c1lBow7aM5J1/EutmHFJVQ9JTjQ=,tag:YbGrI+fZXHXhJ2f12/2cMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zucujcrr89pecplrme76f4vxcc05lg3hm8849mmfggvcvcv4ppls7cquw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMd3lUVDN1TGV6TFltUHhH
            NXFzU2lnMXJkbWpqdnVESjc4eEM1SEI3aUh3CmlIdllheHJJTW9MYldKclY3Tis2
            WTl5U1hlb2RnS1d3SGttYWxXelFQQmcKLS0tIDBSakcvd25KL3UydERzWDNPZUFy
            TVQwbG4yMFRFdGN1MmxnTU91SEFVQXcK0gdXIWfhqlXdtex46/BMyn+fKvblpAdM
            lGE1gs9HEG8rgeiateUhhlX3Ktg9J89Q2JJjta7Db5vKntryzdjdKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-23T11:42:56Z"
    mac: ENC[AES256_GCM,data:i0bdan2JjKMk+PYhce9d0Cjctnv/1rhZ5CM356dhh8gOz1S0QGHpP8Zsmv26VCxjkXmb+Ku5dID6/w/ZrIOyYlDwVmYOa6+KjwVYIJMrO3mrsd8YsNHE/F98AXTp+583UgYqoyM2SsQCga0RNfzwSY36MkofxY3WXRrQbwggeFk=,iv:bGvyj1BClbH0GQQJhoNx0tfdqK9e+sk8KKyoaPk8vpE=,tag:ko+0dW6qdo9GMmHcGVqNsQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
