---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarr-kids
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    name: sonarr-kids-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        SONARR__API_KEY: "{{ .SONARR_KIDS__API_KEY }}"
        PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"
        PUSHOVER_TOKEN: "{{ .PUSHOVER_TOKEN }}"
  dataFrom:
    - extract:
        # PUSHOVER_TOKEN, SONARR_KIDS__API_KEY
        key: sonarr-kids
    - extract:
        # PUSHOVER_USER_KEY
        key: pushover
