---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarr-kids
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sonarr-kids-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        SONARR__API_KEY: "{{ .SONARR_KIDS__API_KEY }}"
        SONARR__POSTGRES_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        SONARR__POSTGRES_PORT: "5432"
        SONARR__POSTGRES_USER: &dbUser "{{ .SONARR_KIDS__POSTGRES_USER }}"
        SONARR__POSTGRES_PASSWORD: &dbPass "{{ .SONARR_KIDS__POSTGRES_PASSWORD }}"
        SONARR__POSTGRES_MAIN_DB: sonarr_kids_main
        SONARR__POSTGRES_LOG_DB: sonarr_kids_log
        PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"
        PUSHOVER_TOKEN: "{{ .PUSHOVER_TOKEN }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: sonarr_kids_main sonarr_kids_log
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

  dataFrom:
    - extract:
        # PUSHOVER_TOKEN, SONARR_KIDS__API_KEY
        key: sonarr-kids
    - extract:
        # PUSHOVER_USER_KEY
        key: pushover
    - extract:
        key: cloudnative-pg
