---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-kids
  namespace: default
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 15Gi
  storageClassName: ceph-filesystem
