---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: audiobookshelf
  namespace: flux-system
spec:
  path: ./kubernetes/talos/apps/media/audiobookshelf/app
  targetNamespace: media
  sourceRef:
    kind: GitRepository
    name: homelab-ops
  commonMetadata:
    labels:
      app.kubernetes.io/name: &appname audiobookshelf
  prune: true
  wait: false
  interval: 10m
  postBuild:
    substitute:
      APP: *appname
      VOLSYNC_CAPACITY: 5Gi