---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: unpackerr
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: unpackerr-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        UN_RADARR_0_API_KEY: "{{ .RADARR__API_KEY }}"
        UN_RADARR_1_API_KEY: "{{ .RADARR_KIDS__API_KEY }}"
        UN_SONARR_0_API_KEY: "{{ .SONARR__API_KEY }}"
        UN_SONARR_1_API_KEY: "{{ .SONARR_KIDS__API_KEY }}"
  dataFrom:
    - extract:
        key: radarr
        # property: RADARR__API_KEY
    - extract:
        key: radarr-kids
        # property: RADARR_KIDS__API_KEY
    - extract:
        key: sonarr
        # property: SONARR__API_KEY
    - extract:
        key: sonarr-kids
        # property: SONARR_KIDS__API_KEY
