apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: beer
spec:
  rules:
  - host: beer.brewcode.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: beer
            port:
              number: 80
