---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: devbu-io
  namespace: networking
spec:
  secretName: devbu-io-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: devbu.io
  dnsNames:
    - devbu.io
    - "*.devbu.io"
