apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:2IjYYtI9cqVKaog83qPkjuvK,iv:924ylbzZe64mJP5m/jFWF63FiQhczRiNFQER46+ai2M=,tag:lSAJ6yls7vX7CxOfpNg8mw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:k1FiUx2bdK9q6O+ertI1onOmZkq7fbB7H7jJPWv8Lz7w1/BJ,iv:6yrJipWEWktIACuUDv53yRjrwlaR8aMlbDL8eehvuuk=,tag:kgQaTmKNay16JAzl5kcbGQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:msJVs0KV3c4YAuRV,iv:JGI434AQ81jwEdjSOTpVkL7s4YaCs3UcYD8TVsuXZ6w=,tag:jwVyx5QPbD9P2OoiJ0bDzQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zucujcrr89pecplrme76f4vxcc05lg3hm8849mmfggvcvcv4ppls7cquw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQy95NDUyNmJHbWdzc0JX
            L0p2aTVKTTFQaWJFS1lFcHhYeFEzTllXWTNFCjM1Y2JIYTh5RCtPV3BuUnJESWJi
            NyttMGgrNVZtU2phc20zdWZ2eGdIZ2MKLS0tIFZYTytNRzNCd0dFR3pGWjl6SG14
            cTU2d3dDRFp2V3NMR09MMGJsWjZxb1UKaQfflx9SFu1w2iuEMFkdfXZ0ctHFu4BR
            SODRVXKIyOLFWhQTVyCXr29cMjVl6KkVdjHxbhjI9jkbB6I0KB/Vhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-22T14:20:29Z"
    mac: ENC[AES256_GCM,data:J1aNPRyV71puaXNfsWQxpbWmRYw3sZv8DbhqAxkG7Bn4NhD65KfvPn+p/tP2u9fIwElQN/87i5Fx4VzueC6JCsx6o0+/zrt63/DeomHh8aw9eTY1VsFMK6ENEfTKNv7j4cyYh0CYBjz8YDqR9fMOSMo/tnklUxf6lovRYgZYLw8=,iv:jH0ENIRGDew5Rxk5uMMKVhe8wyp4ROk+ggCRhGxhdfw=,tag:Z6bGWA8+k7To+SDinU8k7Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
