---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  namespace: storage
  name: longhorn-recurring-jobs
spec:
  targetNamespace: storage
  releaseName: longhorn-recurring-jobs
  timeout: 120s
  chart:
    spec:
      chart: longhorn-recurring-jobs
      version: "5.0.2"
      sourceRef:
        kind: HelmRepository
        name: tyzbit
        namespace: flux-system
  interval: 2m0s
  values:
    minuteStep: 5
    hourStep: 2
    createStorageClasses: true
    storageclass:
      allowVolumeExpansion: true
      reclaimPolicy: Retain
    parameters:
      replicaAutoBalance: best-effort
      dataLocality: best-effort
      numberOfReplicas: "3"
      staleReplicaTimeout: "30"
    groups:
      "Database":
        snapshot:
          - interval: 10m
            retain: 6
        backup:
          - interval: 12h
            retain: 2
      "Gameserver":
        options:
          parameters:
            numberOfReplicas: "2"
        snapshot:
          - interval: 10m
            retain: 6
          - interval: 1h
            retain: 6
        backup:
          - interval: 12h
            retain: 4
      "Plex":
        snapshot:
          - interval: 10m
            retain: 6
        backup:
          - interval: 24h
            retain: 2
      "Config":
        snapshot:
          - interval: 10m
            retain: 6
        backup:
          - interval: 24h
            retain: 7
