---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: longhorn
  namespace: storage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    deletionPolicy: Delete
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      type: Opaque
      data:
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
        AWS_ENDPOINTS: "https://${SECRET_CLOUDFLARE_ACCOUNT_ID}.r2.cloudflarestorage.com"
  data:
    - secretKey: aws-access-key-id
      remoteRef:
        key: cloudnative-pg
        property: AWS_ACCESS_KEY_ID
    - secretKey: aws-secret-access-key
      remoteRef:
        key: cloudnative-pg
        property: AWS_SECRET_ACCESS_KEY
