---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: recyclarr
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: recyclarr-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RADARR_API_KEY: "{{ .RADARR__API_KEY }}"
        RADARR_KIDS_API_KEY: "{{ .RADARR_KIDS__API_KEY }}"
        RADARR_4K_API_KEY: "{{ .RADARR_4K__API_KEY }}"
        SONARR_API_KEY: "{{ .SONARR__API_KEY }}"
  dataFrom:
    - extract:
        key: radarr
        # property: RADARR__API_KEY
    - extract:
        key: radarr_4k
        # property: RADARR_4K__API_KEY
    - extract:
        key: radarr-kids
        # property: RADARR_KIDS__API_KEY
    - extract:
        key: sonarr
        # property: SONARR__API_KEY 
