---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: radarr-kids
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: radarr-kids-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        RADARR__API_KEY: "{{ .RADARR_KIDS__API_KEY }}"
        RADARR__POSTGRES_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        RADARR__POSTGRES_PORT: "5432"
        RADARR__POSTGRES_USER: &dbUser "{{ .RADARR_KIDS__POSTGRES_USER }}"
        RADARR__POSTGRES_PASSWORD: &dbPass "{{ .RADARR_KIDS__POSTGRES_PASSWORD }}"
        RADARR__POSTGRES_MAIN_DB: radarr_kids_main
        RADARR__POSTGRES_LOG_DB: radarr_kids_log
        PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"
        PUSHOVER_TOKEN: "{{ .PUSHOVER_TOKEN }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: radarr_kids_main radarr_kids_log
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: radarr-kids
    - extract:
        key: cloudnative-pg
    - extract:
        key: pushover
