---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tautulli
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 5Gi
  volumeName: tautulli-config
  storageClassName: longhorn
