---
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
sonarr:
  sonarr_main:  # A custom name used to identify this particular instance.
    base_url: http://sonarr.default.svc.cluster.local
    api_key: !env_var SONARR_API_KEY
    delete_old_custom_formats: true
    replace_existing_custom_formats: true

    quality_definition:
      type: series

    quality_profiles:
      - name: WEB-1080p
        reset_unmatched_scores:
          enabled: true
    custom_formats:
      # Scores from TRaSH json
      - trash_ids:
          # Unwanted
          - 85c61753df5da1fb2aab6f2a47426b09  # BR-DISK
          - 9c11cd3f07101cdba90a2d81cf0e56b4  # LQ
          - 47435ece6b99a0b477caf360e79ba0bb  # x265 (HD)

          # Misc
          - ec8fa7296b64e8cd390a1600981f3923  # Repack/Proper
          - eb3d5cc0a2be0db205fb823640db6a3c  # Repack v2
          - 44e7c4de10ae50265753082e5dc76047  # Repack v3

          # Streaming Services
          - d660701077794679fd59e8bdf4ce3a29  # AMZN
          - f67c9ca88f463a48346062e8ad07713f  # ATVP
          - 4e9a630db98d5391aec1368a0256e2fe  # CRAV
          - 36b72f59f4ea20aad9316f475f2d9fbb  # DCU
          - 89358767a60cc28783cdc3d0be9388a4  # DSNP
          - 7a235133c87f7da4c8cccceca7e3c7a6  # HBO
          - a880d6abc21e7c16884f3ae393f84179  # HMAX
          - f6cce30f1733d5c8194222a7507909bb  # HULU
          - 0ac24a2a68a9700bcb7eeca8e5cd644c  # iT
          - 81d1fbf600e2540cee87f3a23f9d3c1c  # MAX
          - d34870697c9db575f17700212167be23  # NF
          - b2b980877494b560443631eb1f473867  # NLZ
          - fb1a91cdc0f26f7ca0696e0e95274645  # OViD
          - 1656adc6d7bb2c8cca6acfb6592db421  # PCOK
          - c67a75ae4a1715f2bb4d492755ba4195  # PMTP
          - 3ac5d84fce98bab1b531393e9c82f467  # QIBI
          - c30d2958827d1867c73318a5a2957eb1  # RED
          - ae58039e1319178e6be73caab5c42166  # SHO
          - 1efe8da11bfd74fbbcd4d8117ddb9213  # STAN
          - 5d2317d99af813b6529c7ebf01c83533  # VDL
          - 77a7b25585c18af08f60b1547bb9b4fb  # CC

          # HQ Source Groups
          - e6258996055b9fbab7e9cb2f75819294  # WEB Tier 01
          - 58790d4e2fdcd9733aa7ae68ba2bb503  # WEB Tier 02
          - d84935abd3f8556dcd51d4f27e22d0a6  # WEB Tier 03
          - d0c516558625b04b363fa6c5c2c7cfd4  # WEB Scene
        quality_profiles:
          - name: WEB-1080p

radarr:
  standard:
    base_url: http://radarr.default.svc.cluster.local
    api_key: !env_var RADARR_API_KEY
    delete_old_custom_formats: true


    include:
      # Comment out any of the following includes to disable them
      - template: radarr-quality-definition-movie
      - template: radarr-quality-profile-remux-web-1080p
      - template: radarr-custom-formats-remux-web-1080p
# Custom Formats: https://recyclarr.dev/wiki/yaml/config-reference/custom-formats/
    custom_formats:
      # Audio
      - trash_ids:
          # Uncomment the next section to enable Advanced Audio Formats
          # - 496f355514737f7d83bf7aa4d24f8169 # TrueHD Atmos
          # - 2f22d89048b01681dde8afe203bf2e95 # DTS X
          # - 417804f7f2c4308c1f4c5d380d4c4475 # ATMOS (undefined)
          # - 1af239278386be2919e1bcee0bde047e # DD+ ATMOS
          # - 3cafb66171b47f226146a0770576870f # TrueHD
          # - dcf3ec6938fa32445f590a4da84256cd # DTS-HD MA
          # - a570d4a0e56a2874b64e5bfa55202a1b # FLAC
          # - e7c2fcae07cbada050a0af3357491d7b # PCM
          # - 8e109e50e0a0b83a5098b056e13bf6db # DTS-HD HRA
          # - 185f1dd7264c4562b9022d963ac37424 # DD+
          # - f9f847ac70a0af62ea4a08280b859636 # DTS-ES
          # - 1c1a4c5e823891c75bc50380a6866f73 # DTS
          # - 240770601cc226190c367ef59aba7463 # AAC
          # - c2998bd0d90ed5621d8df281e839436e # DD
        quality_profiles:
          - name: Remux + WEB 1080p
      # Movie Versions
      - trash_ids:
          - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced
        quality_profiles:
          - name: Remux + WEB 1080p
            # score: 0 # Uncomment this line to disable prioritised IMAX Enhanced releases
      # Optional
      - trash_ids:
          # - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
          # - 90cedc1fea7ea5d11298bebd3d1d3223 # EVO (no WEBDL)
          # - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
          # - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
          # - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
          # - f537cf427b64c38c8e36298f657e4828 # Scene
        quality_profiles:
          - name: Remux + WEB 1080p
      - trash_ids:
          # Uncomment the next six lines to allow x265 HD releases with HDR/DV
          # - dc98083864ea246d05a42df0d05f81cc # x265 (HD)
        # quality_profiles:
          # - name: Remux + WEB 1080p
            # score: 0
      # - trash_ids:
          # - 839bea857ed2c0a8e084f3cbdbd65ecb # x265 (no HDR/DV)
        quality_profiles:
          - name: Remux + WEB 1080p
  kids:
    base_url: http://radarr-kids.default.svc.cluster.local
    api_key: !env_var RADARR_KIDS_API_KEY
    delete_old_custom_formats: true
    quality_definition:
      type: movie
    quality_profiles:
      - name: Remux + WEB 1080p
        reset_unmatched_scores:
          enabled: true
    custom_formats:
      # Scores from TRaSH json
      - trash_ids:
          # Audio - Uncomment the next section if you are using the Advanced Audio Formats
          # - 496f355514737f7d83bf7aa4d24f8169  # TrueHD Atmos
          # - 2f22d89048b01681dde8afe203bf2e95  # DTS X
          # - 417804f7f2c4308c1f4c5d380d4c4475  # ATMOS (undefined)
          # - 1af239278386be2919e1bcee0bde047e  # DD+ ATMOS
          # - 3cafb66171b47f226146a0770576870f  # TrueHD
          # - dcf3ec6938fa32445f590a4da84256cd  # DTS-HD MA
          # - a570d4a0e56a2874b64e5bfa55202a1b  # FLAC
          # - e7c2fcae07cbada050a0af3357491d7b  # PCM
          # - 8e109e50e0a0b83a5098b056e13bf6db  # DTS-HD HRA
          # - 185f1dd7264c4562b9022d963ac37424  # DD+
          # - f9f847ac70a0af62ea4a08280b859636  # DTS-ES
          # - 1c1a4c5e823891c75bc50380a6866f73  # DTS
          # - 240770601cc226190c367ef59aba7463  # AAC
          # - c2998bd0d90ed5621d8df281e839436e  # DD

          # Movie Versions
          - 0f12c086e289cf966fa5948eac571f44  # Hybrid
          - 570bc9ebecd92723d2d21500f4be314c  # Remaster
          - eca37840c13c6ef2dd0262b141a5482f  # 4K Remaster
          - e0c07d59beb37348e975a930d5e50319  # Criterion Collection
          - 9d27d9d2181838f76dee150882bdc58c  # Masters of Cinema
          - db9b4c4b53d312a3ca5f1378f6440fc9  # Vinegar Syndrome
          - 957d0f44b592285f26449575e8b1167e  # Special Edition
          - eecf3a857724171f968a66cb5719e152  # IMAX
          - 9f6cbff8cfe4ebbc1bde14c7b7bec0de  # IMAX Enhanced

          # HQ Release Groups
          - 3a3ff47579026e76d6504ebea39390de  # Remux Tier 01
          - 9f98181fe5a3fbeb0cc29340da2a468a  # Remux Tier 02
          - 8baaf0b3142bf4d94c42a724f034e27a  # Remux Tier 03
          - c20f169ef63c5f40c2def54abaf4438e  # WEB Tier 01
          - 403816d65392c79236dcb6dd591aeda4  # WEB Tier 02
          - af94e0fe497124d1f9ce732069ec8c3b  # WEB Tier 03

          # Misc
          - e7718d7a3ce595f289bfee26adc178f5  # Repack/Proper
          - ae43b294509409a6a13919dedd4764c4  # Repack2

          # Unwanted
          - ed38b889b31be83fda192888e2286d83  # BR-DISK
          - 90a6f9a284dff5103f6346090e6280c8  # LQ
          - dc98083864ea246d05a42df0d05f81cc  # x265 (HD)
          - b8cd450cbfa689c0259a01d9e29ba3d6  # 3D

          # Streaming Services
          - cc5e51a9e85a6296ceefe097a77f12f4  # BCORE
          - 2a6039655313bf5dab1e43523b62c374  # MA
          - 16622a6911d1ab5d5b8b713d5b0036d4  # CRiT
        quality_profiles:
          - name: Remux + WEB 1080p

      # Custom Scoring
      - trash_ids:
          # Streaming Services
          - b3b3a6ac74ecbd56bcdbefa4799fb9df  # AMZN
          - 40e9380490e748672c2522eaaeb692f7  # ATVP
          - f6ff65b3f4b464a79dcc75950fe20382  # CRAV
          - 84272245b2988854bfb76a16e60baea5  # DSNP
          - 509e5f41146e278f9eab1ddaceb34515  # HBO
          - 5763d1b0ce84aff3b21038eea8e9b8ad  # HMAX
          - 526d445d4c16214309f0fd2b3be18a89  # Hulu
          - 6a061313d22e51e0f25b7cd4dc065233  # MAX
          - 170b1d363bd8516fbf3a3eb05d4faff6  # NF
          - fbca986396c5e695ef7b2def3c755d01  # OViD
          - bf7e73dd1d85b12cc527dc619761c840  # Pathe
          - c9fd353f8f5f1baf56dc601c4cb29920  # PCOK
          - e36a0ba1bc902b26ee40818a1d59b8bd  # PMTP
          - c2863d2a50c9acad1fb50e53ece60817  # STAN
        quality_profiles:
          - name: Remux + WEB 1080p
            score: 0
###################################################################################################
# Recyclarr Configuration Template: UHD Bluray + WEB                                              #
# Updated: 2023-08-13                                                                             #
# Documentation: https://recyclarr.dev                                                            #
# Note: If you are using multiple profiles in a single instance, please read the following        #
# documentation about file merging:                                                               #
# https://recyclarr.dev/wiki/yaml/config-examples/#merge-single-instance                          #
###################################################################################################

# Instance Definition
# This section defines your instance type, name, and authentication
# Documentation: https://recyclarr.dev/wiki/yaml/config-reference/basic/
  uhd-bluray-web:
    base_url: http://radarr-4k.default.svc.cluster.local
    api_key: !env_var RADARR_4K_API_KEY

# Quality Definition
# This section defines the Quality Definitions that will be used in your Radarr instance
# Only one set of Quality Definitions can be used per instance
# Documentation: https://recyclarr.dev/wiki/yaml/config-reference/quality-definition/
    quality_definition:
      type: movie

# Quality Profiles
# This section creates and/or updates Quality Profile(s) in your Radarr instance
# Documentation: https://recyclarr.dev/wiki/yaml/config-reference/quality-profiles/
    quality_profiles:
      - name: UHD Bluray + WEB
        reset_unmatched_scores:
          enabled: true
        upgrade:
          allowed: true
          until_quality: Bluray-2160p
          until_score: 10000
        min_format_score: 0
        quality_sort: top
        qualities:
          - name: Bluray-2160p
          - name: WEB 2160p
            qualities:
              - WEBDL-2160p
              - WEBRip-2160p

# Custom Formats
# This section creates and/or updates Custom Formats in your Radarr instance,
# and applies them and their scores to Quality Profiles
# Documentation: https://recyclarr.dev/wiki/yaml/config-reference/custom-formats/
    custom_formats:
      # Scores from TRaSH json
      - trash_ids:
          # Audio - Uncomment the next section if you are using the Advanced Audio Formats
          # - 496f355514737f7d83bf7aa4d24f8169  # TrueHD Atmos
          # - 2f22d89048b01681dde8afe203bf2e95  # DTS X
          # - 417804f7f2c4308c1f4c5d380d4c4475  # ATMOS (undefined)
          # - 1af239278386be2919e1bcee0bde047e  # DD+ ATMOS
          # - 3cafb66171b47f226146a0770576870f  # TrueHD
          # - dcf3ec6938fa32445f590a4da84256cd  # DTS-HD MA
          # - a570d4a0e56a2874b64e5bfa55202a1b  # FLAC
          # - e7c2fcae07cbada050a0af3357491d7b  # PCM
          # - 8e109e50e0a0b83a5098b056e13bf6db  # DTS-HD HRA
          # - 185f1dd7264c4562b9022d963ac37424  # DD+
          # - f9f847ac70a0af62ea4a08280b859636  # DTS-ES
          # - 1c1a4c5e823891c75bc50380a6866f73  # DTS
          # - 240770601cc226190c367ef59aba7463  # AAC
          # - c2998bd0d90ed5621d8df281e839436e  # DD

          # All HDR Formats
          - e23edd2482476e595fb990b12e7c609c  # DV HDR10
          - 58d6a88f13e2db7f5059c41047876f00  # DV
          - 55d53828b9d81cbe20b02efd00aa0efd  # DV HLG
          - a3e19f8f627608af0211acd02bf89735  # DV SDR
          - b974a6cd08c1066250f1f177d7aa1225  # HDR10+
          - dfb86d5941bc9075d6af23b09c2aeecd  # HDR10
          - e61e28db95d22bedcadf030b8f156d96  # HDR
          - 2a4d9069cc1fe3242ff9bdaebed239bb  # HDR (undefined)
          - 08d6d8834ad9ec87b1dc7ec8148e7a1f  # PQ
          - 9364dd386c9b4a1100dde8264690add7  # HLG
          # DV (WEBDL) - The next line is uncommented by default, and ensures that releases with
          # Dolby Vision will only be grabbed if they have HDR10 fallback. You can comment the line
          # out if you do not need HDR10 fallback
          - 923b6abef9b17f937fab56cfcf89e1f1  # DV (WEBDL)
          # HDR10Plus Boost - Uncomment the next line if any of your devices DO support HDR10+
          # - b17886cb4158d9fea189859409975758  # HDR10Plus Boost

          # Movie Versions
          - 570bc9ebecd92723d2d21500f4be314c  # Remaster
          - eca37840c13c6ef2dd0262b141a5482f  # 4K Remaster
          - e0c07d59beb37348e975a930d5e50319  # Criterion Collection
          - 9d27d9d2181838f76dee150882bdc58c  # Masters of Cinema
          - db9b4c4b53d312a3ca5f1378f6440fc9  # Vinegar Syndrome
          - 957d0f44b592285f26449575e8b1167e  # Special Edition
          - eecf3a857724171f968a66cb5719e152  # IMAX
          - 9f6cbff8cfe4ebbc1bde14c7b7bec0de  # IMAX Enhanced

          # HQ Release Groups
          - 4d74ac4c4db0b64bff6ce0cffef99bf0  # UHD Bluray Tier 01
          - a58f517a70193f8e578056642178419d  # UHD Bluray Tier 02
          - e71939fae578037e7aed3ee219bbe7c1  # UHD Bluray Tier 03
          - c20f169ef63c5f40c2def54abaf4438e  # WEB Tier 01
          - 403816d65392c79236dcb6dd591aeda4  # WEB Tier 02
          - af94e0fe497124d1f9ce732069ec8c3b  # WEB Tier 03

          # Misc
          - e7718d7a3ce595f289bfee26adc178f5  # Repack/Proper
          - ae43b294509409a6a13919dedd4764c4  # Repack2

          # Unwanted
          - ed38b889b31be83fda192888e2286d83  # BR-DISK
          - 90a6f9a284dff5103f6346090e6280c8  # LQ
          - dc98083864ea246d05a42df0d05f81cc  # x265 (HD)
          - b8cd450cbfa689c0259a01d9e29ba3d6  # 3D
          - bfd8eb01832d646a0a89c4deb46f8564  # Upscaled
          - 9c38ebb7384dada637be8899efa68e6f  # SDR

          # Streaming Services
          - cc5e51a9e85a6296ceefe097a77f12f4  # BCORE
          - 2a6039655313bf5dab1e43523b62c374  # MA
          - 16622a6911d1ab5d5b8b713d5b0036d4  # CRiT
        quality_profiles:
          - name: UHD Bluray + WEB

      # Custom Scoring
      - trash_ids:
          # Streaming Services
          - b3b3a6ac74ecbd56bcdbefa4799fb9df  # AMZN
          - 40e9380490e748672c2522eaaeb692f7  # ATVP
          - f6ff65b3f4b464a79dcc75950fe20382  # CRAV
          - 84272245b2988854bfb76a16e60baea5  # DSNP
          - 509e5f41146e278f9eab1ddaceb34515  # HBO
          - 5763d1b0ce84aff3b21038eea8e9b8ad  # HMAX
          - 526d445d4c16214309f0fd2b3be18a89  # Hulu
          - 6a061313d22e51e0f25b7cd4dc065233  # MAX
          - 170b1d363bd8516fbf3a3eb05d4faff6  # NF
          - fbca986396c5e695ef7b2def3c755d01  # OViD
          - bf7e73dd1d85b12cc527dc619761c840  # Pathe
          - c9fd353f8f5f1baf56dc601c4cb29920  # PCOK
          - e36a0ba1bc902b26ee40818a1d59b8bd  # PMTP
          - c2863d2a50c9acad1fb50e53ece60817  # STAN
        quality_profiles:
          - name: UHD Bluray + WEB
            score: 0
