---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tandoor
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    name: tandoor-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        SECRET_KEY: "{{ .TANDOOR__SECRET_KEY }}"
        POSTGRES_HOST: &dbHost postgres-rw.database.svc.cluster.local
        POSTGRES_PORT: "5432"
        POSTGRES_USER: &dbUser "{{ .TANDOOR__POSTGRES_USER }}"
        POSTGRES_PASSWORD: &dbPass "{{ .TANDOOR__POSTGRES_PASSWORD }}"
        POSTGRES_DB: tandoor
        # Postgres Init
        INIT_POSTGRES_DBNAME: tandoor
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: tandoor
    - extract:
        key: cloudnative-pg
