---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tandoor
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    initContainers:
      01-init-db:
        image: ghcr.io/onedr0p/postgres-init:14.8
        imagePullPolicy: IfNotPresent
        envFrom: &envFrom
          - secretRef:
              name: tandoor-secret
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: vabene1111/recipes
      tag: 1.5.4@sha256:06ee2b455e74375c69acd545994d929437e59cb96dee44705cf3aa5d5e1d2a97
    env:
      TIMEZONE: Australia/Perth
      ALLOWED_HOSTS: "*"
      DB_ENGINE: django.db.backends.postgresql
    envFrom: *envFrom
    service:
      main:
        ports:
          http:
            port: 8080
    # probes:
    #   liveness: &probes
    #     enabled: true
    #     custom: true
    #     spec:
    #       httpGet:
    #         path: /ping
    #         port: *port
    #       initialDelaySeconds: 0
    #       periodSeconds: 10
    #       timeoutSeconds: 1
    #       failureThreshold: 3
    #   readiness: *probes
    #   startup:
    #     enabled: false
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: &host "{{ .Release.Name }}.brewcode.xyz"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
      fsGroupChangePolicy: OnRootMismatch
      supplementalGroups: [10000]
    volumeClaimTemplates:
      - name: media
        mountPath: /opt/recipes/mediafiles
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: nfs-storage
      - name: static
        mountPath: /opt/recipes/staticfiles
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: nfs-storage
    # persistence:
      # media:
        # enabled: true
        # type: nfs
        # server: 10.1.2.205
        # path: /mnt/dead/media
        # mountPath: /media
    resources:
      requests:
        cpu: 10m
        memory: 250Mi
      limits:
        memory: 2000Mi
