---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app tandoor
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # initContainers:
    #   01-init-db:
    #     image: ghcr.io/onedr0p/postgres-init:14.8
    #     imagePullPolicy: IfNotPresent
    #     envFrom: &envFrom
    #       - secretRef:
    #           name: tandoor-secret
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: vabene1111/recipes
      tag: 1.5.4@sha256:06ee2b455e74375c69acd545994d929437e59cb96dee44705cf3aa5d5e1d2a97
    envFrom: &envFrom
      - secretRef:
          name: tandoor-secret
    env:
      DEBUG: "0"
      TIMEZONE: Australia/Perth
      ALLOWED_HOSTS: "*"
      DB_ENGINE: django.db.backends.postgresql_psycopg2
      GUNICORN_MEDIA: "0"
      TANDOOR_PORT: 8888
      FRACTION_PREF_DEFAULT: "0"
      COMMENT_PREF_DEFAULT: "1"
      SHOPPING_MIN_AUTOSYNC_INTERVAL: "5"
    command:
      - /opt/recipes/venv/bin/gunicorn
      - -b
      - :8888
      - --access-logfile
      - "-"
      - --error-logfile
      - "-"
      - --log-level
      - INFO
      - recipes.wsgi
    service:
      main:
        ports:
          http:
            port: &port 8888
          nginx:
            port: &port2 8080
    # probes:
    #   liveness: &probes
    #     enabled: true
    #     custom: true
    #     spec:
    #       httpGet:
    #         path: /ping
    #         port: *port
    #       initialDelaySeconds: 0
    #       periodSeconds: 10
    #       timeoutSeconds: 1
    #       failureThreshold: 3
    #   readiness: *probes
    #   startup:
    #     enabled: false
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: &host "{{ .Release.Name }}.brewcode.xyz"
            paths: &paths
              - path: /
              - path: /media
                service:
                  port: *port2
              - path: /static
                service:
                  port: *port2
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
      supplementalGroups: [10000]
    volumeClaimTemplates:
      - name: media
        mountPath: /opt/recipes/mediafiles
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: longhorn
    persistence:
      nginx-config:
        enabled: "true"
        mountPath: /etc/nginx/nginx.conf
        subPath: nginx-config
        type: "custom"
        volumeSpec:
          configMap:
            name: tandoor-configmap
      django-js-reverse:
        enabled: true
        type: emptyDir
        mountPath: /opt/recipes/cookbook/static/django_js_reverse
      static:
        enabled: true
        mountPath: /opt/recipes/staticfiles
        type: emptyDir
      cache:
        enabled: true
        mountPath: /mnt/cache
        type: emptyDir
    resources:
      requests:
        cpu: 10m
        memory: 250Mi
      limits:
        memory: 2000Mi
    sidecars:
      nginx:
        image: nginxinc/nginx-unprivileged:1.25.1-alpine
        imagePullPolicy: IfNotPresent
        ports:
          - name: nginx
            containerPort: *port2
        volumeMounts:
          - name: nginx-config
            readOnly: true
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx-config
          - name: media
            mountPath: /media
          - name: static
            mountPath: /static
          - name: cache
            mountPath: /var/cache/nginx
