---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: home-assistant-secret
    template:
      engineVersion: v2
      data:
        # App
        # HASS_DARKSKY_API_KEY: "{{ .HASS_DARKSKY_API_KEY }}"
        # HASS_ECOBEE_API_KEY: "{{ .HASS_ECOBEE_API_KEY }}"
        # HASS_ELEVATION: "{{ .HASS_ELEVATION }}"
        # HASS_GOOGLE_PROJECT_ID: "{{ .HASS_GOOGLE_PROJECT_ID }}"
        # HASS_GOOGLE_SECURE_DEVICES_PIN: "{{ .HASS_GOOGLE_SECURE_DEVICES_PIN }}"
        # HASS_LATITUDE: "{{ .HASS_LATITUDE }}"
        # HASS_LONGITUDE: "{{ .HASS_LONGITUDE }}"
  dataFrom:
    - extract:
        key: home-assistant
